// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMtMn-8JhCaL0vMnBXD8dsfyi-0xUceT8',
    appId: '1:200731379752:web:e59afc4e5bb241a7318d1d',
    messagingSenderId: '200731379752',
    projectId: 'homework-4-7aae8',
    authDomain: 'homework-4-7aae8.firebaseapp.com',
    storageBucket: 'homework-4-7aae8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDht2UuftvzRDmrhh2EPXZs1XaEE03lz5A',
    appId: '1:200731379752:android:982223d754ff5fc2318d1d',
    messagingSenderId: '200731379752',
    projectId: 'homework-4-7aae8',
    storageBucket: 'homework-4-7aae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1C4ipXJKm4uBhLM6um3hlpc8jUcIRgq0',
    appId: '1:200731379752:ios:93d9df64c8ac7e0f318d1d',
    messagingSenderId: '200731379752',
    projectId: 'homework-4-7aae8',
    storageBucket: 'homework-4-7aae8.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1C4ipXJKm4uBhLM6um3hlpc8jUcIRgq0',
    appId: '1:200731379752:ios:93d9df64c8ac7e0f318d1d',
    messagingSenderId: '200731379752',
    projectId: 'homework-4-7aae8',
    storageBucket: 'homework-4-7aae8.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMtMn-8JhCaL0vMnBXD8dsfyi-0xUceT8',
    appId: '1:200731379752:web:7cf8bb94aa3c8ac8318d1d',
    messagingSenderId: '200731379752',
    projectId: 'homework-4-7aae8',
    authDomain: 'homework-4-7aae8.firebaseapp.com',
    storageBucket: 'homework-4-7aae8.firebasestorage.app',
  );

}